# permissions for end users to view baselines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: baseline-viewer-role
rules:
- apiGroups:
  - perf.baseline.io
  resources:
  - baselines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - perf.baseline.io
  resources:
  - baselines/status
  verbs:
  - get
