apiVersion: perf.baseline.io/v1
kind: Baseline
metadata:
  name: baseline-sample
spec:
  cpu: 1			                                # cores
  memory: 1G                                  # size of the virtual memory
  custom: "--timer 1"                         # other custom params
  #image: quay.io/cloud-bulldozer/stressng     # custom image
  # nodeSelector:
  #   stress: "true"
  # tolerations:
  # - key: node-role.kubernetes.io/control-plane
  #   operator: Exists
  #   effect: NoSchedule
  # - key: node-role.kubernetes.io/master
  #   operator: Exists
  #   effect: NoSchedule
