name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login in DockerHub
      run: docker login quay.io -u ${QUAY_USER} -p ${QUAY_TOKEN}
      env:
        QUAYHUB_USER: ${{ secrets.QUAYHUB_USER }}
        QUAYHUB_TOKEN: ${{ secrets.QUAYHUB_TOKEN }}
    - name: Build and push the Docker image
      run: make docker-build docker-push
