name: Makefile CI

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: make test
